[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
solc_version="0.8.15"
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config